### ISSUE TITLE
Prod build routing issue

### ISSUE THREAD

**Issue by ChiragSaxena5437** [pulkitvyas08/Karyakram-Frontend#38]
The routes like '/dashboard' '/events' when are refreshed git ve an error Attached is an example for same.
![image](https://user-images.githubusercontent.com/64087682/160274410-3adec9a5-cd2b-490a-95f4-fa23d776792f.png)

**Comment by pulkitvyas08** [comment]
Yes, the standard `react-router-dom`'s `BrowserRouter` issue, let me take a look
